spring.application.name=To-DoList
server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=book007tita13

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
